# Generated by Django 5.1.7 on 2025-07-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
    ]
