# Generated by Django 5.2 on 2025-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='initial_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
