# Generated by Django 5.1.7 on 2025-11-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_remove_supervisor_user_student_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='Admin',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Management.admin'),
        ),
    ]
