# Generated by Django 5.1.7 on 2025-11-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_alter_supervisor_admin'),
        ('StudentTasks', '0007_alter_weeklyreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentTasks.contract'),
        ),
    ]
