# Generated by Django 5.1.7 on 2025-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_task_task_id_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttask',
            old_name='datecomplited',
            new_name='date_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
