# Generated by Django 5.1.7 on 2026-01-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0009_rename_datecomplited_studenttask_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
