# Generated by Django 5.1.7 on 2025-07-02 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='UWS intern Contract', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('total_hours', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='weeklytask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('task_list', models.TextField(blank=True)),
                ('absent_days', models.PositiveIntegerField(default=0, help_text='Number of absent days this week')),
                ('hours_spent', models.FloatField()),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='PENDING', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_days', to='StudentTasks.contract')),
            ],
            options={
                'ordering': ['-week_num'],
                'unique_together': {('contract', 'week_num')},
            },
        ),
    ]
