# Generated by Django 5.2 on 2025-07-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentTasks', '0002_alter_contract_student_alter_weeklytask_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentTasks.contract'),
        ),
    ]
