# Generated by Django 5.1.7 on 2025-11-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_alter_student_user'),
        ('StudentTasks', '0004_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_contracts', to='Management.supervisor'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
