# Generated by Django 5.1.7 on 2025-11-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_remove_supervisor_user_student_status_and_more'),
        ('StudentTasks', '0005_contract_supervisor_alter_weeklytask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AlterUniqueTogether(
            name='weeklytask',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklytask',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='student',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=20, unique=True)),
                ('week_num', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('daily_duties', models.TextField(help_text='Describe daily tasks performed during the week.')),
                ('absent_days', models.PositiveIntegerField(default=0, help_text='Number of absent days this week')),
                ('hours_spent', models.FloatField()),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='StudentTasks.contract')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='Management.student')),
            ],
            options={
                'ordering': ['-week_num'],
                'unique_together': {('contract', 'week_num')},
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='weeklytask',
        ),
    ]
