# Generated by Django 5.1.7 on 2025-11-17 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_alter_supervisor_admin'),
        ('StudentTasks', '0006_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('student', 'week_num')},
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='Management.supervisor'),
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='contract',
        ),
    ]
