# Generated by Django 5.1.7 on 2026-03-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentTasks', '0007_alter_weeklyreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
    ]
